/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdminFolder;

import DatabaseConnection.Studentdb;
import examinationManagementSystem.*;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Adminsignup extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    Connection con = Studentdb.getConnection();
    PreparedStatement ps;
    
    public Adminsignup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public int getMaxAdmin()
    {
        int id = 0;
        Statement st;
        try {
            st= con.createStatement();
            ResultSet rs = st.executeQuery("select max(id) from admin");
            while (rs.next())
            {                
                id = rs.getInt(1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return id+1;
    }
    public String getHashPassword(String pass)
    {
        byte[] b = pass.getBytes();
        StringBuffer hexString = null ;
        String hexEachByteValue="" ;
        try 
        {
            MessageDigest algo = MessageDigest.getInstance("MD5");
            algo.reset();
            algo.update(b);
            byte hash[]= algo.digest();
            
            hexString = new StringBuffer();
            for(int i = 0; i<hash.length;i++)
            {
              hexEachByteValue = Integer.toHexString(0xFF & hash[i]);        // eta character asole ek ek ta 
              if(hexEachByteValue.length()==1)
              {
                  hexString.append('0');
              }
              hexString.append(hexEachByteValue);
            }
//            System.out.println("hex is " + hex);
            System.out.println("hexString is " +hexString);
            System.out.println("hexString is " +hexString.toString());
        }
        catch (Exception e) {
        }
        return hexString.toString();
    }
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        btnSignUp = new javax.swing.JButton();
        btnLogIn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtComboQs = new javax.swing.JComboBox<>();
        txtAns = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examinationManagementSystem/about.png"))); // NOI18N
        jLabel1.setText("SIGN UP");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Password :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 70, 20));

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Username :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 70, 20));
        jPanel1.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 250, -1));

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Full name :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 70, 20));
        jPanel1.add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 250, -1));

        txtPass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtPass.setForeground(new java.awt.Color(102, 102, 102));
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 250, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("I've an account");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 100, -1));

        btnSignUp.setBackground(new java.awt.Color(0, 102, 102));
        btnSignUp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUp.setText("Sign up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        jPanel1.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 100, 40));

        btnLogIn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogIn.setIcon(new javax.swing.ImageIcon("F:\\Netbeans\\Examination Management System\\project Image\\login1.png")); // NOI18N
        btnLogIn.setText("Login");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Security Question");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Security Answer");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        txtComboQs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your father's name ?", "What is your mother's name ?" }));
        jPanel1.add(txtComboQs, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 250, -1));
        jPanel1.add(txtAns, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 250, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 510, 440);

        setBounds(0, 0, 529, 451);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed

        AdminLogin logInFrame = new AdminLogin();
        logInFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogInActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        
        int id = getMaxAdmin();
        String fullName = txtFullName.getText();
        String userName = txtUserName.getText();
        String pass = txtPass.getText();
        
        String hashpass = getHashPassword(pass);
        
        System.out.println("hashPass : "+hashpass);
        String securityQs = txtComboQs.getSelectedItem().toString();
        String securityAns = txtAns.getText();

        try {
            ps = con.prepareStatement("insert into admin values(?,?,?,?,?,?)");
            ps.setInt(1, id);
            ps.setString(2, userName);    // username Rahul password Rahul hashvalue save hbe rahul er
            ps.setString(3, hashpass); // save the  hashvalue of password
            ps.setString(4, fullName);
            ps.setString(5, securityQs);
            ps.setString(6, securityAns);
            
            if(ps.executeUpdate()>0)
            {
                JOptionPane.showMessageDialog(null, "New Admin added successfully ");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Adminsignup.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adminsignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adminsignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adminsignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adminsignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adminsignup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAns;
    private javax.swing.JComboBox<String> txtComboQs;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
