/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdminFolder;

//import com.sun.jdi.connect.spi.Connection;
import DatabaseConnection.Studentdb;
import examinationManagementSystem.*;
import com.mysql.cj.protocol.Resultset;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Admin
 */
public class AdminLogin extends javax.swing.JFrame 
{
    Connection con;
    PreparedStatement psmt;
    Statement smt;
    ResultSet rs;
    
    public AdminLogin() {
        initComponents();
        con= Studentdb.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        txtUserName = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnForget = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("UserName :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 154, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Password :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 194, -1, -1));

        txtPass.setText("jPasswordField1");
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 219, -1));
        jPanel1.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 219, -1));

        btnCancel.setIcon(new javax.swing.ImageIcon("F:\\Netbeans\\Examination Management System\\project Image\\cancel1.png")); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 262, -1, -1));

        btnSignUp.setBackground(new java.awt.Color(0, 102, 0));
        btnSignUp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUp.setText("SignUp");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        jPanel1.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 323, 80, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon("F:\\Netbeans\\Examination Management System\\project Image\\login.png")); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 80));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 31, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("I don't have an account");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        btnLogin.setIcon(new javax.swing.ImageIcon("F:\\Netbeans\\Examination Management System\\project Image\\login1.png")); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 262, -1, -1));

        btnForget.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnForget.setText("Forget Password");
        btnForget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForgetActionPerformed(evt);
            }
        });
        jPanel1.add(btnForget, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(573, 448));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public String getHashPassword(String pass)
    {
        byte[] b = pass.getBytes();
        StringBuffer hexString = null ;
        String hexEachByteValue="" ;
        try 
        {
            MessageDigest algo = MessageDigest.getInstance("MD5");
            algo.reset();
            algo.update(b);
            byte hash[]= algo.digest();
            
            hexString = new StringBuffer();
            for(int i = 0; i<hash.length;i++)
            {
              hexEachByteValue = Integer.toHexString(0xFF & hash[i]);        // eta character asole ek ek ta 
              if(hexEachByteValue.length()==1)
              {
                  hexString.append('0');
              }
              hexString.append(hexEachByteValue);
            }
//            System.out.println("hex is " + hex);
            System.out.println("hexString is " +hexString);
            System.out.println("hexString is " +hexString.toString());
        }
        catch (Exception e) {
        }
        return hexString.toString();
    }
    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed

        Adminsignup signFrame = new Adminsignup();
        signFrame.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String userName = txtUserName.getText();
        String pass = txtPass.getText();
        String hashPass = getHashPassword(pass);            //password change to hashvalue
        System.out.println("hash in login "+ hashPass);
        try
        {
            psmt= con.prepareStatement("select * from admin where username = ? and password = ?");  
            psmt.setString(1, userName);  
            psmt.setString(2, hashPass);   // hashvalue of password is save

            rs= psmt.executeQuery();
            if(rs.next()==false)
            {
                JOptionPane.showMessageDialog(this, "Sign up in first .");
            }
            else{
                JOptionPane.showMessageDialog(this, "log in successful .");
                Home hm = new Home(userName,pass);
                hm.setVisible(true);
                this.dispose();
            }
        }    
        catch (Exception e) 
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnForgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgetActionPerformed

        ForgetPassword fg = new ForgetPassword();
        fg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnForgetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnForget;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}



