

package exxtraPages;

import DatabaseConnection.Studentdb;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Admin
 */
public class FillUpForm extends javax.swing.JFrame 
{
    Connection con;
    PreparedStatement psmt;
    Statement smt;
    ResultSet rs;
    
    public FillUpForm() 
    {
        initComponents();
        con= Studentdb.getConnection();

        
    }
    public ImageIcon resizeImage(String imagePath, byte[] pic ,int wd , int ht)
    {
        ImageIcon myImg = null;
        
        if(imagePath != null)
        {
            myImg = new ImageIcon(imagePath);
        }
        else
        {
            myImg = new ImageIcon(pic);
        }
        Image img = myImg.getImage();
        Image img2 = img.getScaledInstance(wd, ht, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        return image;
            
    }
    public String getPathOfPicture()
    {
        String path = "";
        JFileChooser jfChooser = new JFileChooser();
        jfChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("images", "jpg","png");
        jfChooser.addChoosableFileFilter(filter);
        int result= jfChooser.showSaveDialog(null);
        if(result==JFileChooser.APPROVE_OPTION)
        {
            File selectfile= jfChooser.getSelectedFile();
            path = selectfile.getAbsolutePath();                  //String
        }
        else
        {
            System.out.println("no file selected");
        }
        return path;
        
    }
    //check input fields
    public boolean checkInputs()
    {
        if(txtName.getText()==null||txtDob.getText()==null||txtPhNo.getText()==null||txtAddress.getText()==null||txtEmail.getText()==null||txtAppDate.getText()==null||
           txtFatherName.getText()==null||txtQualDate.getText()==null    
               )
        {
            return false;
        }
        else
        {
//            try
//            {
//                Float.parseFloat(txtTranjaction.getText());
//                return true;
//                
//            }catch{
//                return false;
//            }
            return true;
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        calendarPanel1 = new com.github.lgooddatepicker.components.CalendarPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        txtName = new javax.swing.JTextField();
        txtFatherName = new javax.swing.JTextField();
        txtPicPath = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        txtPhNo = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        txtDob = new com.github.lgooddatepicker.components.DatePicker();
        jLabel10 = new javax.swing.JLabel();
        txtAppDate = new com.github.lgooddatepicker.components.DatePicker();
        jLabel11 = new javax.swing.JLabel();
        txtSignPicPath = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jComboBoxQual = new javax.swing.JComboBox<>();
        txtQualDate = new com.github.lgooddatepicker.components.DatePicker();
        txtMarks = new javax.swing.JTextField();
        btnSignImg = new javax.swing.JButton();
        btnPicImg = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jComboBoxZone = new javax.swing.JComboBox<>();
        lblSignPicimg = new javax.swing.JLabel();
        lblPicimg = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnSubmit4 = new javax.swing.JButton();
        btnSubmit5 = new javax.swing.JButton();
        btnSubmit6 = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Date of Birth");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Father's Name :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 51, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Phone No :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 85, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Adress :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel5.setText("Gender :");
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Email :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 122, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Picture :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, -1, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Male");
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, -1, -1));
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 14, 248, -1));

        txtFatherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFatherNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtFatherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 48, 248, -1));

        txtPicPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPicPathActionPerformed(evt);
            }
        });
        jPanel1.add(txtPicPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 170, -1));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 248, -1));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 381, 248, 0));

        txtPhNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhNoActionPerformed(evt);
            }
        });
        jPanel1.add(txtPhNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 82, 248, -1));

        btnBack.setIcon(new javax.swing.ImageIcon("F:\\Netbeans\\Examination Management System\\project Image\\back.png")); // NOI18N
        btnBack.setText("Back");
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 90, 30));

        btnSubmit.setIcon(new javax.swing.ImageIcon("F:\\Netbeans\\Examination Management System\\project Image\\submit.png")); // NOI18N
        btnSubmit.setText("Last");
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 620, -1, 30));

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 250, 80));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Name :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
        jPanel1.add(txtDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Application Date");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, -1));
        jPanel1.add(txtAppDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Signature :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, -1, -1));

        txtSignPicPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSignPicPathActionPerformed(evt);
            }
        });
        jPanel1.add(txtSignPicPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 170, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setText("Qualification Details");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 250, 38));

        jLabel14.setText("Percentage of Marks :");
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Qualification Date :");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setText("Qualification Details");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 1, 250, 38));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Roll :");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Qualification ID :");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Qualification Date :");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 620, 230));

        jLabel20.setText("Qualification ID :");
        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jComboBoxQual.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MATRICULATION 1", "HIGHER SECONDARY 2", "GRADUATE 3", "POST GRADUATE 4", "DIPLOMA 5" }));
        jPanel2.add(jComboBoxQual, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 140, 20));
        jPanel2.add(txtQualDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        txtMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarksActionPerformed(evt);
            }
        });
        jPanel2.add(txtMarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 180, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 400, 160));

        btnSignImg.setText("...");
        btnSignImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignImgActionPerformed(evt);
            }
        });
        jPanel1.add(btnSignImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, 20, -1));

        btnPicImg.setText("...");
        btnPicImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPicImgActionPerformed(evt);
            }
        });
        jPanel1.add(btnPicImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 20, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("SELECT EXAM ZONE :");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, -1, -1));

        jComboBoxZone.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KOLKATA", "HOWRAH", "HOOGLY", "BANKURA" }));
        jComboBoxZone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxZoneActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxZone, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 140, -1));

        lblSignPicimg.setText("jLabel22");
        lblSignPicimg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lblSignPicimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 100, 100));

        lblPicimg.setText("jLabel22");
        lblPicimg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblPicimg.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(lblPicimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 100, 100));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Phno", "Email", "Tranjaction Id", "RollNo"
            }
        ));
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(5);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 530, 550));

        btnUpdate.setIcon(new javax.swing.ImageIcon("F:\\Netbeans\\Examination Management System\\project Image\\update icon.png")); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 620, -1, -1));

        btnDelete.setIcon(new javax.swing.ImageIcon("F:\\Netbeans\\Examination Management System\\project Image\\delete_16x16.gif")); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 620, -1, -1));

        btnInsert.setIcon(new javax.swing.ImageIcon("F:\\Netbeans\\Examination Management System\\project Image\\submit.png")); // NOI18N
        btnInsert.setText("Insert");
        btnInsert.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        jPanel1.add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 620, -1, 30));

        btnSubmit4.setIcon(new javax.swing.ImageIcon("F:\\Netbeans\\Examination Management System\\project Image\\submit.png")); // NOI18N
        btnSubmit4.setText("First");
        btnSubmit4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSubmit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmit4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 620, -1, 30));

        btnSubmit5.setIcon(new javax.swing.ImageIcon("F:\\Netbeans\\Examination Management System\\project Image\\submit.png")); // NOI18N
        btnSubmit5.setText("Next");
        btnSubmit5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSubmit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmit5ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmit5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 620, -1, 30));

        btnSubmit6.setIcon(new javax.swing.ImageIcon("F:\\Netbeans\\Examination Management System\\project Image\\submit.png")); // NOI18N
        btnSubmit6.setText("Prev");
        btnSubmit6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSubmit6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmit6ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmit6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 620, -1, 30));
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 190, -1));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 789));

        setSize(new java.awt.Dimension(1156, 697));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtFatherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFatherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFatherNameActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void txtPhNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhNoActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void txtPicPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPicPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPicPathActionPerformed

    private void txtSignPicPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSignPicPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSignPicPathActionPerformed

    private void btnSignImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignImgActionPerformed
        // TODO add your handling code here:
        String signPath = getPathOfPicture();
        lblSignPicimg.setIcon(resizeImage(signPath, null, lblSignPicimg.getWidth(), lblSignPicimg.getHeight()));
        txtSignPicPath.setText(signPath);
        
    }//GEN-LAST:event_btnSignImgActionPerformed

    private void jComboBoxZoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxZoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxZoneActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    
    int i = 6;
    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        
        
        
//        InputStream fisImgPic;
//        try {
//
//
//        } catch (FileNotFoundException ex) {
//            Logger.getLogger(FillUpForm.class.getName()).log(Level.SEVERE, null, ex);
//        }
        
        
        if(checkInputs())  // means true      //&&ImgPath!= null
        {
            
//         SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
//         String dobDate = sdf.format(txtDob.getDate());
//         String appDate = sdf.format(txtAppDate.getDate());
//         String QualDate = sdf.format(txtQualDate.getDate());
            try {
//                InputStream fisImgPic = new FileInputStream(new File(txtPicPath.getText()));
//                InputStream fisImgSign = new FileInputStream(new File(txtSignPicPath.getText()));
                
//                PreparedStatement psmt = con.prepareStatement("INSERT INTO student(Id,Name,Dob,Gender,Guardian,PhoneNo,Email,Address,FormDate,QualDate,Marks,Zone) values(?,?,?,?,?,?,?,?,?,?,?,?)");  //
                PreparedStatement psmt = con.prepareStatement("INSERT INTO student(Id,Name,Dob,Gender,Guardian,PhoneNo,Email,Address,FormDate,QualDate) values(?,?,?,?,?,?,?,?,?,?)");  //
                System.out.println("before execute");
                
                psmt.setInt(1,Integer.parseInt(txtId.getText()));    //id
                
                System.out.println(" id generate "+i);
                psmt.setString(2, txtName.getText());    //name
                psmt.setString(3, txtDob.toString());              //dob
                psmt.setString(4, "M");                      //gender
                psmt.setString(5, txtFatherName.getText());   //father name 
                psmt.setString(6, txtPhNo.getText());        //ph no
                psmt.setString(7, txtEmail.getText());        //mail
                psmt.setString(8, txtAddress.getText());                    // application date
                psmt.setString(9, txtAppDate.toString());                    // application date
//                psmt.setBlob(4, fisImgSign);           
//                psmt.setBlob(11, fisImgPic);
//                psmt.setInt(12, 1);             // qual id 1
                psmt.setString(10, txtQualDate.toString());
//problem                psmt.setInt(11, Integer.parseInt(txtName.getText()));         // marks in int
//                psmt.setString(12, jComboBoxZone.getSelectedItem().toString());
//                
                System.out.println("Ready to execute");
                psmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Register successfully");

            } catch (SQLException ex) {
                Logger.getLogger(FillUpForm.class.getName()).log(Level.SEVERE, null, ex);
///            } catch (FileNotFoundException ex) {
 //               Logger.getLogger(FillUpForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "One more field are empty");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnSubmit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmit4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmit4ActionPerformed

    private void btnSubmit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmit5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmit5ActionPerformed

    private void btnSubmit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmit6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmit6ActionPerformed

    private void btnPicImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPicImgActionPerformed

          String picPath = getPathOfPicture();
          lblPicimg.setIcon(resizeImage(picPath, null, lblPicimg.getWidth(), lblPicimg.getHeight()));
          txtPicPath.setText(picPath);

    }//GEN-LAST:event_btnPicImgActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FillUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FillUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FillUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FillUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FillUpForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnPicImg;
    private javax.swing.JButton btnSignImg;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnSubmit4;
    private javax.swing.JButton btnSubmit5;
    private javax.swing.JButton btnSubmit6;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.github.lgooddatepicker.components.CalendarPanel calendarPanel1;
    private javax.swing.JComboBox<String> jComboBoxQual;
    private javax.swing.JComboBox<String> jComboBoxZone;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel lblPicimg;
    private javax.swing.JLabel lblSignPicimg;
    private javax.swing.JTextArea txtAddress;
    private com.github.lgooddatepicker.components.DatePicker txtAppDate;
    private com.github.lgooddatepicker.components.DatePicker txtDob;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFatherName;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMarks;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhNo;
    private javax.swing.JTextField txtPicPath;
    private com.github.lgooddatepicker.components.DatePicker txtQualDate;
    private javax.swing.JTextField txtSignPicPath;
    // End of variables declaration//GEN-END:variables
}




















//        JFileChooser jfChooser = new JFileChooser();
//        jfChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
//        FileNameExtensionFilter filter = new FileNameExtensionFilter("images", "jpg","png");
//        jfChooser.addChoosableFileFilter(filter);
//        int result= jfChooser.showSaveDialog(null);
//        if(result==JFileChooser.APPROVE_OPTION)
//        {
//            File selectfile= jfChooser.getSelectedFile();
//            String path = selectfile.getAbsolutePath();
//            lblPicimg.setIcon(resizeImage(path, null, lblPicimg.getWidth(), lblPicimg.getHeight()));
//        }
//        else
//        {
//            System.out.println("No file selected . ");
//        }